let data = [
  {
    id: 1,
    name: "Work on garden",
    dateCreated: "12.06.2021",
    category: "Task",
    context: "water the trees",
    planDate: "13.06.2021",
    archive: true,
  },
  {
    id: 2,
    name: "Going to meeting with star",
    dateCreated: "28.06.2021",
    category: "Task",
    context: "Random Thoughts",
    planDate: "29.06.2021",
    archive: false,
  },
  {
    id: 3,
    name: "Going to meeting with star",
    dateCreated: "28.06.2021",
    category: "Task",
    context: "Random Thoughts",
    planDate: "29.06.2021",
    archive: false,
  },
  {
    id: 4,
    name: "Going to meeting with star",
    dateCreated: "28.06.2021",
    category: "Task",
    context: "Random Thoughts",
    planDate: "29.06.2021",
    archive: false,
  },
  {
    id: 5,
    name: "Going to meeting with star",
    dateCreated: "28.06.2021",
    category: "Task",
    context: "Random Thoughts",
    planDate: "29.06.2021",
    archive: false,
  },
  {
    id: 6,
    name: "Going to meeting with star",
    dateCreated: "28.06.2021",
    category: "Task",
    context: "Random Thoughts",
    planDate: "29.06.2021",
    archive: false,
  },
  {
    id: 7,
    name: "Going to meeting with star",
    dateCreated: "28.06.2021",
    category: "Task",
    context: "Random Thoughts",
    planDate: "29.06.2021",
    archive: false,
  },
];

module.exports=data;